import ApplicationServices

/// Element role.
public struct Role: Identifier {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let application = Self(rawValue: kAXApplicationRole)
    public static let systemWide = Self(rawValue: kAXSystemWideRole)
    public static let window = Self(rawValue: kAXWindowRole)
    public static let sheet = Self(rawValue: kAXSheetRole)
    public static let drawer = Self(rawValue: kAXDrawerRole)
    public static let growArea = Self(rawValue: kAXGrowAreaRole)
    public static let image = Self(rawValue: kAXImageRole)
    public static let unknown = Self(rawValue: kAXUnknownRole)
    public static let button = Self(rawValue: kAXButtonRole)
    public static let radioButton = Self(rawValue: kAXRadioButtonRole)
    public static let checkBox = Self(rawValue: kAXCheckBoxRole)
    public static let popUpButton = Self(rawValue: kAXPopUpButtonRole)
    public static let menuButton = Self(rawValue: kAXMenuButtonRole)
    public static let tabGroup = Self(rawValue: kAXTabGroupRole)
    public static let table = Self(rawValue: kAXTableRole)
    public static let column = Self(rawValue: kAXColumnRole)
    public static let row = Self(rawValue: kAXRowRole)
    public static let outline = Self(rawValue: kAXOutlineRole)
    public static let browser = Self(rawValue: kAXBrowserRole)
    public static let scrollArea = Self(rawValue: kAXScrollAreaRole)
    public static let scrollBar = Self(rawValue: kAXScrollBarRole)
    public static let radioGroup = Self(rawValue: kAXRadioGroupRole)
    public static let list = Self(rawValue: kAXListRole)
    public static let group = Self(rawValue: kAXGroupRole)
    public static let valueIndicator = Self(rawValue: kAXValueIndicatorRole)
    public static let comboBox = Self(rawValue: kAXComboBoxRole)
    public static let slider = Self(rawValue: kAXSliderRole)
    public static let incrementer = Self(rawValue: kAXIncrementorRole)
    public static let busyIndicator = Self(rawValue: kAXBusyIndicatorRole)
    public static let progressIndicator = Self(rawValue: kAXProgressIndicatorRole)
    public static let relevanceIndicator = Self(rawValue: kAXRelevanceIndicatorRole)
    public static let toolbar = Self(rawValue: kAXToolbarRole)
    public static let disclosureTriangle = Self(rawValue: kAXDisclosureTriangleRole)
    public static let textField = Self(rawValue: kAXTextFieldRole)
    public static let textArea = Self(rawValue: kAXTextAreaRole)
    public static let staticText = Self(rawValue: kAXStaticTextRole)
    public static let heading = Self(rawValue: kAXHeadingRole)
    public static let menuBar = Self(rawValue: kAXMenuBarRole)
    public static let menuBarItem = Self(rawValue: kAXMenuBarItemRole)
    public static let menu = Self(rawValue: kAXMenuRole)
    public static let menuItem = Self(rawValue: kAXMenuItemRole)
    public static let splitGroup = Self(rawValue: kAXSplitGroupRole)
    public static let splitter = Self(rawValue: kAXSplitterRole)
    public static let colorWell = Self(rawValue: kAXColorWellRole)
    public static let timeField = Self(rawValue: kAXTimeFieldRole)
    public static let dateField = Self(rawValue: kAXDateFieldRole)
    public static let helpTag = Self(rawValue: kAXHelpTagRole)
    public static let matte = Self(rawValue: kAXMatteRole)
    public static let dockItem = Self(rawValue: kAXDockItemRole)
    public static let ruler = Self(rawValue: kAXRulerRole)
    public static let grid = Self(rawValue: kAXGridRole)
    public static let levelIndicator = Self(rawValue: kAXLevelIndicatorRole)
    public static let cell = Self(rawValue: kAXCellRole)
    public static let layoutArea = Self(rawValue: kAXLayoutAreaRole)
    public static let layoutItem = Self(rawValue: kAXLayoutItemRole)
    public static let handle = Self(rawValue: kAXHandleRole)
    public static let popover = Self(rawValue: kAXPopoverRole)
    public static let link = Self(rawValue: "AXLink")
    public static let webArea = Self(rawValue: "AXWebArea")
    public static let genericElement = Self(rawValue: "AXGenericElement")
}